[project]
name = "electrode"
authors = [
    {name = "blindelectron", email = "jump.leper@gmail.com"},
]
version = "0.1.0"
description = "A powerfull audio game engine written in python."
readme = "README.md"
license = {text = "LGPL-3.0-only"}
requires-python = ">=3.11,<3.13"
dependencies = [
    "cyal>=0.3.2,<1.0.0",
    "pybullet>=3.2.5,<4.0.0",
    "numpy>=1.26.2,<2.0.0",
    "webcolors>=1.13,<2.0",
    "wxpython>=4.2.1,<5.0.0",
    "soundfile>=0.12.1,<1.0.0",
    "pyttsx4>=3.0.15,<4.0.0",
    "wxasync>=0.49,<1.0",
    # "accessible-output3>=0.1.2,<1.0.0",
]

[dependency-groups]
more_tts = [
    "gtts>=2.5.0,<3.0.0",
]
